# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'USMPTest1' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for USMPTest1
pod "BSImagePicker", "~> 2.4"

  target 'USMPTest1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
